"""empty message

Revision ID: 45f42de589f5
Revises: 005f3ee08dcc
Create Date: 2023-10-04 14:07:40.267670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f42de589f5'
down_revision = '005f3ee08dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_invitees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AcceptanceStatus', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_invitees', schema=None) as batch_op:
        batch_op.drop_column('AcceptanceStatus')

    # ### end Alembic commands ###
